services:
  db:
    image: postgis/postgis:17-3.5
    container_name: postgres
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data/

  proxy:
    image: traefik:v3.6.2
    command:
      - "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedByDefault=false"
      - "--providers.docker.network=call_centre-ndt"
      - "--accesslog=true"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.web.forwardedHeaders.insecure=true"
      - "--entrypoints.metrics.address=:8082"
      - "--metrics.prometheus.entryPoint=metrics"
    ports:
      - "8082:8082"
      - "80:80"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.11.0
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - xpack.security.enrollment.enabled=false
      - xpack.security.http.ssl.enabled=false
      - xpack.security.transport.ssl.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - es_data:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
    networks:
      - elastic-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9200"]
      interval: 30s
      timeout: 10s
      retries: 5

  kibana:
    image: docker.elastic.co/kibana/kibana:8.11.0
    container_name: kibana
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      - ELASTICSEARCH_REQUESTTIMEOUT=60000
    ports:
      - "5601:5601"
    networks:
      - elastic-network
    depends_on:
      elasticsearch:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5601/api/status"]
      interval: 30s
      timeout: 10s
      retries: 5

  zookeeper:
    image: confluentinc/cp-zookeeper:7.1.0
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:7.1.0
    container_name: kafka
    ports:
      - "9092:9092"
      - "29093:29093"
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: LISTENER_DOCKER_INTERNAL:PLAINTEXT,LISTENER_DOCKER_EXTERNAL:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: LISTENER_DOCKER_INTERNAL://kafka:29093,LISTENER_DOCKER_EXTERNAL://localhost:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: LISTENER_DOCKER
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  auth_service:
    build:
      context: .
      dockerfile: Dockerfile
    image: call_centre:latest
    container_name: call_centre
    env_file:
      - .env
    environment:
      - POSTGRES_HOST=db
    depends_on:
      - db
    command: >
      uvicorn apps.auth_service.main:app --host 0.0.0.0 --port 8080 --workers 1 --root-path /auth
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.entrypoints=web"
      - "traefik.http.routers.auth.rule=PathPrefix(`/auth`)"
      - "traefik.http.services.auth.loadbalancer.server.port=8080"
      - "traefik.http.routers.auth.middlewares=auth-stripprefix"
      - "traefik.http.middlewares.auth-stripprefix.stripprefix.prefixes=/auth"


  chat_service:
    image: call_centre:latest
    env_file:
      - .env
    environment:
      - POSTGRES_HOST=db
    depends_on:
      - db
    command: >
      uvicorn apps.chat_service.main:app --host 0.0.0.0 --port 8080 --workers 1 --root-path /chat
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.entrypoints=web"
      - "traefik.http.routers.chat.rule=PathPrefix(`/chat`)"
      - "traefik.http.services.chat.loadbalancer.server.port=8080"
      - "traefik.http.routers.chat.middlewares=chat-stripprefix"
      - "traefik.http.middlewares.chat-stripprefix.stripprefix.prefixes=/chat"


volumes:
  pg_data:
  es_data:
    driver: local

networks:
  elastic-network:
    driver: bridge
