services:
  db:
    image: postgis/postgis:17-3.5
    container_name: postgres
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data/

  proxy:
    image: traefik:v3.6.2
    command:
      - "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedByDefault=false"
      - "--providers.docker.network=call_centre-ndt"
      - "--accesslog=true"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.web.forwardedHeaders.insecure=true"
      - "--entrypoints.metrics.address=:8082"
      - "--metrics.prometheus.entryPoint=metrics"
    ports:
      - "8082:8082"
      - "80:80"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.11.0
    container_name: elasticsearch
    environment:
      - node.name=elasticsearch
      - cluster.name=es-docker-cluster
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - es_data:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
      - "9300:9300"

  auth_service:
    build:
      context: .
      dockerfile: Dockerfile
    image: call_centre:latest
    container_name: call_centre
    env_file:
      - .env
    environment:
      - POSTGRES_HOST=db
    depends_on:
      - db
    command: >
      uvicorn apps.auth_service.main:app --host 0.0.0.0 --port 8080 --workers 1 --root-path /auth
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.entrypoints=web"
      - "traefik.http.routers.auth.rule=PathPrefix(`/auth`)"
      - "traefik.http.services.auth.loadbalancer.server.port=8080"
      - "traefik.http.routers.auth.middlewares=auth-stripprefix"
      - "traefik.http.middlewares.auth-stripprefix.stripprefix.prefixes=/auth"


  chat_service:
    image: call_centre:latest
    env_file:
      - .env
    environment:
      - POSTGRES_HOST=db
    depends_on:
      - db
    command: >
      uvicorn apps.chat_service.main:app --host 0.0.0.0 --port 8080 --workers 1 --root-path /chat
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.entrypoints=web"
      - "traefik.http.routers.chat.rule=PathPrefix(`/chat`)"
      - "traefik.http.services.chat.loadbalancer.server.port=8080"
      - "traefik.http.routers.chat.middlewares=chat-stripprefix"
      - "traefik.http.middlewares.chat-stripprefix.stripprefix.prefixes=/chat"


volumes:
  pg_data:
  es_data:
    driver: local