"""add_is_online_and_last_activity_date_to_user

Revision ID: 2026_04_13_0642
Revises: 13a73fcddd0a
Create Date: 2026-04-13 06:42:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2026_04_13_0642'
down_revision: Union[str, Sequence[str], None] = '13a73fcddd0a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('auth_user', sa.Column('is_online', sa.Boolean(), nullable=False, server_default='false'))
    op.add_column('auth_user', sa.Column('last_activity_date', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('auth_user', 'last_activity_date')
    op.drop_column('auth_user', 'is_online')
    # ### end Alembic commands ###