"""relations

Revision ID: 13a73fcddd0a
Revises: ca222fc27206
Create Date: 2026-03-05 10:10:59.040929

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '13a73fcddd0a'
down_revision: Union[str, Sequence[str], None] = 'ca222fc27206'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_message', sa.Column('chat_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'chat_message', 'chat_chat', ['chat_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'chat_message', type_='foreignkey')
    op.drop_column('chat_message', 'chat_id')
    # ### end Alembic commands ###
